/* =====================================================================
   pdf-export.js

   Fills the WotC fillable PDF (assets/5E_CharacterSheet_Fillable.pdf) with
   a character's data + current session state, returns the bytes for
   download. Lazy-loaded by sheet.js on Download PDF button click.

   Design notes:
   * Field names taken directly from the PDF AcroForm (some have trailing
     spaces, e.g. "Race ", "DEXmod ", "Deception "). Match exactly.
   * Spell row -> level mapping is derived from on-page geometry, not
     numeric order. The mapping below was generated by inspecting each
     "Spells <id>" field's y position on page 2.
   * Things the PDF can't represent (resource pips, racial trait list,
     subclass spell-list note) get dumped into the Features and Traits
     and Equipment text fields with structured prefixes.
   ===================================================================== */

// Map ability key -> PDF score field, mod field, save proficiency checkbox
const ABILITY_FIELDS = {
  str: { score: 'STR', mod: 'STRmod',  saveProf: 'Check Box 11' },
  dex: { score: 'DEX', mod: 'DEXmod ', saveProf: 'Check Box 18' },
  con: { score: 'CON', mod: 'CONmod',  saveProf: 'Check Box 19' },
  int: { score: 'INT', mod: 'INTmod',  saveProf: 'Check Box 20' },
  wis: { score: 'WIS', mod: 'WISmod',  saveProf: 'Check Box 21' },
  cha: { score: 'CHA', mod: 'CHamod',  saveProf: 'Check Box 22' },
};

// Map skill name -> PDF text field + proficiency checkbox
const SKILL_FIELDS = {
  'Acrobatics':      { text: 'Acrobatics',       prof: 'Check Box 23' },
  'Animal Handling': { text: 'Animal',           prof: 'Check Box 24' },
  'Arcana':          { text: 'Arcana',           prof: 'Check Box 25' },
  'Athletics':       { text: 'Athletics',        prof: 'Check Box 26' },
  'Deception':       { text: 'Deception ',       prof: 'Check Box 27' },
  'History':         { text: 'History ',         prof: 'Check Box 28' },
  'Insight':         { text: 'Insight',          prof: 'Check Box 29' },
  'Intimidation':    { text: 'Intimidation',     prof: 'Check Box 30' },
  'Investigation':   { text: 'Investigation ',   prof: 'Check Box 31' },
  'Medicine':        { text: 'Medicine',         prof: 'Check Box 32' },
  'Nature':          { text: 'Nature',           prof: 'Check Box 33' },
  'Perception':      { text: 'Perception ',      prof: 'Check Box 34' },
  'Performance':     { text: 'Performance',      prof: 'Check Box 35' },
  'Persuasion':      { text: 'Persuasion',       prof: 'Check Box 36' },
  'Religion':        { text: 'Religion',         prof: 'Check Box 37' },
  'Sleight of Hand': { text: 'SleightofHand',    prof: 'Check Box 38' },
  'Stealth':         { text: 'Stealth ',         prof: 'Check Box 39' },
  'Survival':        { text: 'Survival',         prof: 'Check Box 40' },
};

// Map ability key -> save bonus text field
const SAVE_TEXT = {
  str: 'ST Strength',
  dex: 'ST Dexterity',
  con: 'ST Constitution',
  int: 'ST Intelligence',
  wis: 'ST Wisdom',
  cha: 'ST Charisma',
};

// Death save checkboxes (top row = successes, bottom row = failures)
const DEATH_SUCCESS = ['Check Box 12', 'Check Box 13', 'Check Box 14'];
const DEATH_FAILURE = ['Check Box 15', 'Check Box 16', 'Check Box 17'];

// Spell row -> field names, ordered by visual y position on page 2.
// Derived from PDF inspection. Within a level, fill rows in this order;
// any spells beyond the available slots overflow into AttacksSpellcasting.
const SPELL_ROWS = {
  0: ['Spells 1014', 'Spells 1016', 'Spells 1017', 'Spells 1018', 'Spells 1019', 'Spells 1020', 'Spells 1021', 'Spells 1022'],
  1: ['Spells 1015', 'Spells 1023', 'Spells 1024', 'Spells 1025', 'Spells 1026', 'Spells 1027', 'Spells 1028', 'Spells 1029', 'Spells 1030', 'Spells 1031', 'Spells 1032', 'Spells 1033'],
  2: ['Spells 1046', 'Spells 1034', 'Spells 1035', 'Spells 1036', 'Spells 1037', 'Spells 1038', 'Spells 1039', 'Spells 1040', 'Spells 1041', 'Spells 1042', 'Spells 1043', 'Spells 1044', 'Spells 1045'],
  3: ['Spells 1048', 'Spells 1047', 'Spells 1049', 'Spells 1050', 'Spells 1051', 'Spells 1052', 'Spells 1053', 'Spells 1054', 'Spells 1055', 'Spells 1056', 'Spells 1057', 'Spells 1058', 'Spells 1059'],
  4: ['Spells 1061', 'Spells 1060', 'Spells 1062', 'Spells 1063', 'Spells 1064', 'Spells 1065', 'Spells 1066', 'Spells 1067', 'Spells 1068', 'Spells 1069', 'Spells 1070', 'Spells 1071', 'Spells 1072'],
  5: ['Spells 1074', 'Spells 1073', 'Spells 1075', 'Spells 1076', 'Spells 1077', 'Spells 1078', 'Spells 1079', 'Spells 1080', 'Spells 1081'],
  6: ['Spells 1083', 'Spells 1082', 'Spells 1084', 'Spells 1085', 'Spells 1086', 'Spells 1087', 'Spells 1088', 'Spells 1089', 'Spells 1090'],
  7: ['Spells 1092', 'Spells 1091', 'Spells 1093', 'Spells 1094', 'Spells 1095', 'Spells 1096', 'Spells 1097', 'Spells 1098', 'Spells 1099'],
  8: ['Spells 10101', 'Spells 10100', 'Spells 10102', 'Spells 10103', 'Spells 10104', 'Spells 10105', 'Spells 10106'],
  9: ['Spells 10108', 'Spells 10107', 'Spells 10109', 'Spells 101010', 'Spells 101011', 'Spells 101012', 'Spells 101013'],
};

const ATTACK_SLOTS = [
  { name: 'Wpn Name',   atk: 'Wpn1 AtkBonus',   dmg: 'Wpn1 Damage' },
  { name: 'Wpn Name 2', atk: 'Wpn2 AtkBonus ',  dmg: 'Wpn2 Damage ' },
  { name: 'Wpn Name 3', atk: 'Wpn3 AtkBonus  ', dmg: 'Wpn3 Damage ' },
];

function fmtMod(n) { return (n >= 0 ? '+' : '') + n; }
function abilityMod(score) { return Math.floor((score - 10) / 2); }

function safeSet(form, name, value) {
  try {
    const f = form.getTextField(name);
    f.setText(String(value ?? ''));
  } catch (e) {
    // field doesn't exist or wrong type, skip silently
  }
}

function safeCheck(form, name, on) {
  try {
    const cb = form.getCheckBox(name);
    if (on) cb.check(); else cb.uncheck();
  } catch (e) {}
}

export async function fillCharacterPdf(character, state, templateBuffer, PDFDocument) {
  const pdfDoc = await PDFDocument.load(templateBuffer);
  const form = pdfDoc.getForm();

  const c = character;
  const s = state;

  const profBonus = c.profBonus;
  const abilities = Object.fromEntries(c.abilities.map(a => [a.key, a.score]));
  const mods = Object.fromEntries(c.abilities.map(a => [a.key, abilityMod(a.score)]));
  const spellAbility = c.spellcastingAbility;

  // Header / identity
  safeSet(form, 'CharacterName', c.identity.name);
  safeSet(form, 'ClassLevel',    c.identity.classLine);
  safeSet(form, 'Background',    c.identity.background);
  safeSet(form, 'Race ',         c.identity.classLine?.split(/\s+/)[0] || '');
  safeSet(form, 'Alignment',     s.alignment || '');
  safeSet(form, 'XP',            s.xp || '');
  safeSet(form, 'Speed',         (c.identity.speedLine || '').replace(/^Speed\s*/i, ''));

  // Ability scores + mods
  for (const [key, fields] of Object.entries(ABILITY_FIELDS)) {
    safeSet(form, fields.score, abilities[key]);
    safeSet(form, fields.mod, fmtMod(mods[key]));
  }

  // Saves: bonus text + proficient checkbox
  for (const save of (c.saves || [])) {
    const bonus = mods[save.ability] + (save.proficient ? profBonus : 0);
    safeSet(form, SAVE_TEXT[save.ability], fmtMod(bonus));
    safeCheck(form, ABILITY_FIELDS[save.ability].saveProf, save.proficient);
  }

  // Skills: bonus text + proficient checkbox
  for (const sk of (c.skills || [])) {
    const fields = SKILL_FIELDS[sk.name];
    if (!fields) continue;
    const bonus = mods[sk.ability] + (sk.proficient ? profBonus : 0);
    safeSet(form, fields.text, fmtMod(bonus));
    safeCheck(form, fields.prof, sk.proficient);
  }

  // Combat
  safeSet(form, 'AC',         c.combat.ac);
  safeSet(form, 'Initiative', fmtMod(mods.dex));
  safeSet(form, 'ProfBonus',  fmtMod(profBonus));
  safeSet(form, 'Inspiration', s.inspiration ? '1' : '');
  safeSet(form, 'Passive',    10 + mods.wis + (c.skills?.find(x => x.name === 'Perception')?.proficient ? profBonus : 0));
  safeSet(form, 'HPMax',      c.combat.hpMax);
  safeSet(form, 'HPCurrent',  s.hp.current);
  safeSet(form, 'HPTemp',     s.hp.temp || '');
  safeSet(form, 'HDTotal',    `${c.combat.hitDiceMax}${c.combat.hitDiceType}`);
  safeSet(form, 'HD',         s.hitDice);

  // Death saves
  DEATH_SUCCESS.forEach((cb, i) => safeCheck(form, cb, !!s.deathSaves?.successes?.[i]));
  DEATH_FAILURE.forEach((cb, i) => safeCheck(form, cb, !!s.deathSaves?.failures?.[i]));

  // Spell DC + atk
  if (spellAbility && mods[spellAbility] !== undefined) {
    safeSet(form, 'SpellSaveDC  2',   8 + profBonus + mods[spellAbility]);
    safeSet(form, 'SpellAtkBonus 2',  fmtMod(profBonus + mods[spellAbility]));
    safeSet(form, 'Spellcasting Class 2', c.identity.classLine);
    safeSet(form, 'SpellcastingAbility 2', spellAbility.toUpperCase());
  }

  // Currencies (all into GP for now since the engine only tracks gold)
  safeSet(form, 'GP', s.gold ?? 0);

  // Languages + Proficiencies (combined, the PDF has one field)
  const profs = [c.identity.languages, c.identity.otherProficiencies].filter(Boolean).join('\n');
  safeSet(form, 'ProficienciesLang', profs);

  // Attacks: first 3 weapons go to the table rows, rest goes to the
  // AttacksSpellcasting overflow text field.
  const attacks = c.attacks || [];
  attacks.slice(0, 3).forEach((a, i) => {
    safeSet(form, ATTACK_SLOTS[i].name, a.name);
    safeSet(form, ATTACK_SLOTS[i].atk,  a.atk);
    safeSet(form, ATTACK_SLOTS[i].dmg,  a.notes);
  });
  const overflowAttacks = attacks.slice(3).map(a => `${a.name} ${a.atk} - ${a.notes}${a.extra ? ' (' + a.extra + ')' : ''}`);
  // Plus reaction
  const reactionLine = c.reaction ? [`Reaction: ${c.reaction.title} - ${c.reaction.desc}`] : [];

  // Spells: place each known spell in the right level row by order.
  // Track overflow per level.
  const overflow = [];
  if (Array.isArray(c.spells)) {
    const used = {};
    for (const sp of c.spells) {
      const lvl = sp.lvl ?? 0;
      const rows = SPELL_ROWS[lvl];
      if (!rows) continue;
      const idx = used[lvl] = (used[lvl] || 0);
      if (idx < rows.length) {
        safeSet(form, rows[idx], sp.name);
        used[lvl] = idx + 1;
      } else {
        overflow.push(`${sp.lvlLabel || 'lvl ' + lvl}: ${sp.name}`);
      }
    }
  }
  // Limited spells (racials, scrolls) get appended to overflow with a tag
  if (Array.isArray(c.limitedSpells)) {
    for (const ls of c.limitedSpells) {
      overflow.push(`${ls.group}: ${ls.name}${ls.meta ? ' (' + ls.meta + ')' : ''}`);
    }
  }

  // AttacksSpellcasting: reaction + attack overflow + spell overflow + spellSource note
  const atkSpellLines = [
    ...reactionLine,
    ...(overflowAttacks.length ? ['Extra attacks:', ...overflowAttacks.map(l => '  ' + l)] : []),
    ...(overflow.length ? ['Overflow spells:', ...overflow.map(l => '  ' + l)] : []),
    ...(c.spellSource ? [c.spellSource] : []),
  ];
  if (atkSpellLines.length) safeSet(form, 'AttacksSpellcasting', atkSpellLines.join('\n'));

  // Equipment: dump inventory list (state.inventory is the runtime version
  // including session adds; falls back to character.defaultInventory)
  const inv = (s.inventory && s.inventory.length) ? s.inventory : (c.defaultInventory || []);
  const eqLines = inv.map(i => i.notes ? `${i.name} - ${i.notes}` : i.name);
  safeSet(form, 'Equipment', eqLines.join('\n'));

  // Features and Traits: features list + racial traits + class resources
  // (which the PDF has no slots for, so they go here as text)
  const featLines = [];
  if (c.racialTraits?.length) {
    featLines.push('Racial traits:');
    c.racialTraits.forEach(t => featLines.push(`  ${t.name}${t.desc ? ' - ' + t.desc : ''}`));
    featLines.push('');
  }
  if (c.resources?.length) {
    featLines.push('Class resources:');
    c.resources.forEach(r => {
      const stateVal = s.resources?.[r.key];
      let cur;
      if (r.type === 'pip' && Array.isArray(stateVal)) cur = stateVal.filter(v => !v).length;
      else if (r.type === 'counter') cur = stateVal;
      else if (r.type === 'toggle') cur = stateVal ? 'used' : 'available';
      else cur = '?';
      featLines.push(`  ${r.name}: ${cur}/${r.max ?? '-'} (${r.restoresOn} rest)`);
    });
    featLines.push('');
  }
  if (c.features?.length) {
    let lastGroup = null;
    c.features.forEach(f => {
      if (f.group && f.group !== lastGroup) {
        featLines.push(`${f.group}:`);
        lastGroup = f.group;
      }
      const indent = f.group ? '  ' : '';
      const tag = f.tag ? ` (${f.tag})` : '';
      const upcoming = f.upcoming ? ' [upcoming]' : '';
      featLines.push(`${indent}${f.name}${tag}${upcoming}: ${f.desc}`);
    });
  }
  safeSet(form, 'Features and Traits', featLines.join('\n'));

  // Treasure: any homebrew rules text
  if (c.homebrew && c.homebrew.trim()) {
    safeSet(form, 'Treasure', c.homebrew);
  }

  // Flatten? Keep editable so the player can hand-edit afterwards.
  // form.flatten();

  return await pdfDoc.save();
}
