#!/usr/bin/env python3
"""
scripts/build-readme.py

Regenerates the auto-managed page list inside README.md. Each entry is
derived from the page's <meta name="description"> tag. The README has
marker comments around the section so the rest of the file stays
hand-authored.

Usage:
    python3 scripts/build-readme.py            # rewrite README.md in place
    python3 scripts/build-readme.py --check    # exit 1 if README is stale

Run after adding, removing, or renaming a page that's linked from the
sidebar. The sanitize script runs --check on every push.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"

# Sidebar structure. Mirrors sidebar.js. When you add a new sidebar entry,
# add it here too (keep them in lockstep).
SECTIONS = [
    ("Films", [
        ("/films/filmclub.html",       "Filmclub"),
    ]),
    ("Projects", [
        ("/projects/saltysnacks.html",  "Saltysnacks"),
        ("/projects/fantasyfootball.html", "FPL Predicted XI"),
        ("/projects/happyhour.html",    "Happy Hour"),
        ("/projects/worldcup.html",     "World Cup 2026"),
        ("/projects/flox/index.html",   "Flox"),
        ("/projects/search.html",       "Search"),
    ]),
    ("Games", [
        ("/dnd/index.html",             "dnd"),
        ("/projects/duoclue/index.html", "Duoclue"),
        ("/games/magic.html",           "Magic"),
    ]),
    ("Wren", [
        ("/shelf/index.html",           "Shelf"),
        ("/wren/negative-space.html",   "Negative Space"),
    ]),
]

BEGIN = "<!-- BEGIN: pages (auto-generated by scripts/build-readme.py) -->"
END   = "<!-- END: pages -->"


def read_description(href: str) -> str:
    """Pull the <meta name="description"> content from a page."""
    path = ROOT / href.lstrip("/")
    if not path.exists():
        raise SystemExit(f"missing page: {href}")
    text = path.read_text(encoding="utf-8")
    m = re.search(r'<meta\s+name="description"\s+content="([^"]+)"', text)
    if not m:
        raise SystemExit(f"page has no <meta name=\"description\">: {href}")
    return m.group(1).strip()


def render() -> str:
    """Build the markdown block that goes between the markers.

    Format: bold title on its own line followed by a colon, description
    on the next line. Blank line between entries. No inline page link.
    Reads visually consistent regardless of title length.
    """
    lines = [BEGIN, ""]
    for section, pages in SECTIONS:
        lines.append(f"### {section}")
        lines.append("")
        for href, label in pages:
            desc = read_description(href)
            # Markdown collapses single newlines into a space. <br> forces
            # the description onto its own line under the title, in every
            # markdown renderer, including GitHub.
            lines.append(f"**{label}:**<br>")
            lines.append(desc)
            lines.append("")
    lines.append(END)
    return "\n".join(lines)


def replace_region(readme_text: str, generated: str) -> str:
    """Swap the BEGIN..END region in README with `generated`."""
    pattern = re.escape(BEGIN) + r".*?" + re.escape(END)
    if re.search(pattern, readme_text, flags=re.DOTALL):
        return re.sub(pattern, generated, readme_text, count=1, flags=re.DOTALL)
    # First run: append the region with a leading blank line.
    sep = "" if readme_text.endswith("\n\n") else ("\n" if readme_text.endswith("\n") else "\n\n")
    return readme_text + sep + generated + "\n"


def main() -> int:
    check = "--check" in sys.argv

    current = README.read_text(encoding="utf-8") if README.exists() else ""
    new = replace_region(current, render())

    if check:
        if current != new:
            print("README.md is out of date. Run: python3 scripts/build-readme.py")
            return 1
        print("README.md is up to date.")
        return 0

    if current == new:
        print("README.md unchanged.")
        return 0

    README.write_text(new, encoding="utf-8")
    print("README.md updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
